workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        NODE_VERSION: 16  # تحديد إصدار Node.js
    scripts:
      - name: Install npm and dependencies
        script: |
          npm install -g npm@latest  # تحديث npm
          npm install -g npx         # تثبيت npx إذا لم يكن مثبتًا
          npm install                # تثبيت التبعيات للمشروع
      - name: Build iOS app
        script: |
          npx eas build -p ios --non-interactive  # بناء التطبيق باستخدام EAS
    artifacts:
      - build/ios/*.ipa  # حفظ ملف .ipa الناتج
